import type { PublicationFile } from "../shared/artifacts.ts";
import { canonicalJson, requireArtifactPath } from "./artifact-validation.ts";
import { type BlobStore, hashBytes } from "./blobs.ts";
import {
  hasLegacyFileBytes,
  type LegacyRow,
  legacyId,
  legacyObject,
  legacySeq,
  legacyText,
  type MigrationContext,
} from "./migration-data.ts";
import { validateStoredPatch } from "./patch-content.ts";
import {
  type DocumentRenderer,
  type PreparedFile,
  prepareFiles,
  type ValidatedPublication,
  validatePublication,
} from "./publication.ts";

export type LegacyCapture = (
  review: LegacyRow,
  repo: LegacyRow | null,
) => Promise<
  | { kind: "files"; files: PublicationFile[] }
  | { kind: "diff"; patch: string }
  | { unavailable: string }
>;

// Old snapshots had a per-file bound, but no directory count/total bound.
// Import their retained membership without applying a new upload quota; all
// path, byte, media-type, and per-file validation remains in force.
export const validateHistoricalPublication = (value: unknown) =>
  validatePublication(value, {
    files: Number.MAX_SAFE_INTEGER,
    totalBytes: Number.MAX_SAFE_INTEGER,
  });

function migrationNotice(): PublicationFile {
  return {
    path: "MIGRATION.md",
    mediaType: "text/markdown; charset=utf-8",
    base64: Buffer.from(
      "# Content unavailable after migration\n\nThis notice was generated by r3 during migration. No original files were retained for this publication. The original snapshot metadata and missing-file evidence are preserved in its provenance. Publish a complete directory to continue this artifact.\n",
    ).toString("base64"),
  };
}

// Missing historical sequences remain reserved, including references to deleted
// rounds. Store ranges instead of expanding an arbitrarily large sequence gap.
function missingRanges(max: number, present: number[]): [number, number][] {
  const ranges: [number, number][] = [];
  let start = 1;
  for (const seq of [...present].sort((a, b) => a - b)) {
    if (seq > start) ranges.push([start, seq - 1]);
    start = seq + 1;
  }
  if (start <= max) ranges.push([start, max]);
  return ranges;
}

function reservedSequence(context: MigrationContext, review: LegacyRow): number {
  const id = review.id;
  const feedbackIds = new Set(
    context.data.feedback.filter((r) => r.review_id === id).map((r) => r.id),
  );
  const values = [
    ...context.data.patches.filter((r) => r.review_id === id).map((r) => r.seq),
    ...context.data.snapshots.filter((r) => r.review_id === id).map((r) => r.seq),
    ...context.data.snapshot_files.filter((r) => r.review_id === id).map((r) => r.seq),
    ...context.data.feedback.filter((r) => r.review_id === id).map((r) => r.patch_seq),
    ...context.data.replies
      .filter((r) => feedbackIds.has(r.feedback_id))
      .flatMap((r) => [r.patch_seq, r.ref_version]),
  ];
  let max = 0;
  for (const value of values) {
    if (value === null || value === undefined || value === 0) continue;
    const seq = legacySeq(value);
    if (seq === null || !Number.isSafeInteger(seq + 2))
      throw new Error("Invalid legacy version sequence");
    max = Math.max(max, seq);
  }
  return max;
}

export async function importLegacyContent(
  context: MigrationContext,
  blobs: BlobStore,
  render: DocumentRenderer,
  capture?: LegacyCapture,
): Promise<void> {
  const { db, data, time } = context;
  const projectDefaults = new Map<string, unknown>();
  for (const repo of data.repos) {
    const defaults = context.defaults(`project:${legacyId(repo.id)}`);
    db.query("INSERT INTO projects(id, name, remote_url, created_at) VALUES (?, ?, ?, ?)").run(
      legacyId(repo.id),
      legacyText(repo.name),
      legacyText(repo.remote),
      defaults.time("createdAt", repo.created_at),
    );
    projectDefaults.set(legacyId(repo.id), defaults.records);
  }
  for (const review of data.reviews) {
    const id = legacyId(review.id);
    const kind = review.kind === "diff" ? "diff" : "files";
    if (!["diff", "files", "doc"].includes(String(review.kind)))
      throw new Error("Unknown legacy review kind");
    const defaults = context.defaults(`artifact:${id}`);
    const createdAt = defaults.time("createdAt", review.created_at);
    const updatedAt = defaults.time("updatedAt", review.updated_at, createdAt);
    const oldMeta = legacyObject(review.meta);
    const meta = Object.fromEntries(
      Object.entries(oldMeta).filter(([, value]) => typeof value === "string"),
    );
    if (JSON.stringify(oldMeta) !== JSON.stringify(meta))
      defaults.record("meta", meta, "Non-string legacy metadata remains in provenance");
    const creator = defaults.actor("createdBy", review.created_by, oldMeta.session, createdAt);
    const state =
      review.status === "approved" || review.status === "abandoned" ? "archived" : "active";
    if (review.status !== "open")
      defaults.record(
        "state",
        state,
        "Mapped the legacy lifecycle; original outcome remains in provenance",
      );
    const max = reservedSequence(context, review);
    context.writeSessions();
    const repo = data.repos.find((row) => row.id === review.repo_id) ?? null;
    if (review.repo_id && !repo)
      defaults.record("projectId", null, "Legacy project record is absent");
    db.query(`INSERT INTO artifacts(id, kind, state, project_id, title, summary, meta_json,
      created_by, creator_session_id, next_seq, created_at, updated_at, archived_at)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`).run(
      id,
      kind,
      "active",
      repo ? legacyId(repo.id) : null,
      legacyText(review.title),
      legacyText(review.summary),
      canonicalJson(meta),
      creator.role,
      creator.sessionId,
      1,
      createdAt,
      updatedAt,
      null,
    );

    const present: number[] = [];
    const unavailable: Record<string, unknown>[] = [];
    const versions = (kind === "diff" ? data.patches : data.snapshots)
      .filter((row) => row.review_id === id)
      .sort((a, b) => Number(a.seq) - Number(b.seq));
    for (const version of versions) {
      const seq = legacySeq(version.seq);
      if (seq === null) throw new Error("Legacy publication has no valid sequence");
      const versionDefaults = context.defaults(`version:${id}:${seq}`);
      const versionTime = versionDefaults.time("createdAt", version.created_at, createdAt);
      const publisher = versionDefaults.actor("publishedBy", undefined, undefined, versionTime);
      let publication: ValidatedPublication;
      const evidence: Record<string, unknown> = { ...version };
      delete evidence.body;
      if (kind === "diff") {
        const patch = legacyText(version.body);
        try {
          if (!patch) throw new Error("No retained patch body");
          validateStoredPatch(patch);
        } catch (error) {
          unavailable.push({
            ...version,
            reason: error instanceof Error ? error.message : "Invalid retained patch",
          });
          continue;
        }
        publication = {
          kind,
          patch,
          files: [],
          entrypoint: null,
          expectedSeq: 0,
          publicationKey: `migration:snapshot:${seq}`,
          actor: publisher,
          label: legacyText(version.label),
          summary: legacyText(version.summary),
          provenance: {},
          contentHash: hashBytes(canonicalJson({ kind, patch })),
        };
      } else {
        const members = data.snapshot_files.filter(
          (row) => row.review_id === id && row.seq === seq,
        );
        const missing = members.filter((row) => !hasLegacyFileBytes(row));
        const files = members.filter(hasLegacyFileBytes).map((row) => ({
          path: requireArtifactPath(row.path),
          mediaType: Bun.file(String(row.path)).type || "application/octet-stream",
          base64: Buffer.from(row.content as string).toString("base64"),
        }));
        evidence.members = members.map(({ content: _, ...row }) => row);
        evidence.missing = missing;
        evidence.completeness =
          "Legacy text snapshots did not retain binary resources or prove complete directory membership";
        if (!files.length) {
          files.push(migrationNotice());
          versionDefaults.record(
            "files",
            ["MIGRATION.md"],
            "Generated a notice because no original member bytes survived",
          );
        }
        // Historical data is trusted storage, but its path/membership still has
        // to be safe to serve. Never silently reinterpret a skipped marker as
        // an original zero-byte file.
        publication = validateHistoricalPublication({
          expectedSeq: 0,
          publicationKey: `migration:snapshot:${seq}`,
          actor: publisher,
          content: { kind, files },
        });
        publication.label = legacyText(version.label);
      }
      publication.provenance = {
        migration: { at: time, source: evidence, defaults: versionDefaults.records },
      };
      await insertVersion(context, blobs, render, id, seq, publication, versionTime);
      present.push(seq);
    }

    let captureResult: Record<string, unknown> = {
      unavailable: "No local capture adapter was supplied",
    };
    // A sticky stored-round marker must never fall back to today's git diff.
    const canCapture = kind === "files" || (!review.stored_rounds && !versions.length);
    if (capture && canCapture) {
      const result = await capture(review, repo);
      captureResult = "unavailable" in result ? result : { captured: true };
      if (!("unavailable" in result)) {
        if (result.kind !== kind) throw new Error("Legacy capture changed artifact kind");
        let captured: { publication: ValidatedPublication; files: PreparedFile[] } | null = null;
        try {
          const publication = validatePublication({
            expectedSeq: 0,
            publicationKey: "migration:current",
            actor: { role: "human", sessionId: null },
            label: "Captured during migration",
            content: result,
            provenance: { migration: { at: time, currentCapture: true, historical: false } },
          });
          captured = { publication, files: await prepareFiles(publication, blobs, render) };
        } catch (error) {
          // Today's files may no longer be publishable. This must not prevent
          // importing retained history; preserve why the optional capture failed.
          captureResult = {
            unavailable: error instanceof Error ? error.message : "Current capture is invalid",
          };
        }
        if (captured) {
          await insertVersion(
            context,
            blobs,
            render,
            id,
            max + 1,
            captured.publication,
            time,
            captured.files,
          );
          present.push(max + 1);
        }
      }
    }
    if (!present.length && kind === "files") {
      const publication = validatePublication({
        expectedSeq: 0,
        publicationKey: "migration:notice",
        actor: { role: "human", sessionId: null },
        label: "Migration notice",
        content: { kind, files: [migrationNotice()] },
        provenance: {
          migration: {
            at: time,
            synthetic: ["MIGRATION.md"],
            reason: "No retained publication or current capture",
            capture: captureResult,
          },
        },
      });
      await insertVersion(context, blobs, render, id, max + 1, publication, time);
      present.push(max + 1);
    }
    db.query(
      "UPDATE artifacts SET next_seq = ?, legacy_json = ?, state = ?, archived_at = ? WHERE id = ?",
    ).run(
      Math.max(max, ...present) + 1,
      JSON.stringify({
        migration: {
          at: time,
          source: review,
          project: repo,
          projectDefaults: repo ? projectDefaults.get(legacyId(repo.id)) : [],
          defaults: defaults.records,
          missingVersions: missingRanges(
            max,
            present.filter((seq) => seq <= max),
          ),
          unavailable,
          currentCapture: captureResult,
        },
      }),
      state,
      state === "archived" ? updatedAt : null,
      id,
    );
    if (state === "archived") {
      db.query(`INSERT INTO artifact_events(id, artifact_id, event, operation_key, actor, created_at)
        VALUES (?, ?, 'archived', 'migration:archive', 'human', ?)`).run(
        `migration_archive_${hashBytes(id).slice(0, 32)}`,
        id,
        updatedAt,
      );
    }
  }
}

async function insertVersion(
  context: MigrationContext,
  blobs: BlobStore,
  render: DocumentRenderer,
  id: string,
  seq: number,
  publication: ValidatedPublication,
  time: string,
  prepared?: PreparedFile[],
): Promise<void> {
  const { db } = context;
  const files = prepared ?? (await prepareFiles(publication, blobs, render));
  db.query("UPDATE artifacts SET next_seq = ? WHERE id = ?").run(seq + 1, id);
  db.query(`INSERT INTO artifact_versions(artifact_id, seq, kind, publication_key, content_hash,
    label, summary, published_by, publisher_session_id, provenance_json, entrypoint, patch_body, file_count, created_at)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`).run(
    id,
    seq,
    publication.kind,
    publication.publicationKey,
    publication.contentHash,
    publication.label,
    publication.summary,
    publication.actor.role,
    publication.actor.sessionId,
    JSON.stringify(publication.provenance),
    null,
    publication.patch,
    publication.kind === "diff" ? null : files.length,
    time,
  );
  for (const file of files) {
    for (const blob of [file, file.rendered]) {
      if (blob)
        db.query(
          "INSERT INTO blobs(hash, byte_length, created_at) VALUES (?, ?, ?) ON CONFLICT(hash) DO NOTHING",
        ).run(blob.hash, blob.byteLength, time);
    }
    db.query(`INSERT INTO version_files(artifact_id, version_seq, artifact_kind, path, media_type,
      blob_hash, rendered_blob_hash, renderer_revision) VALUES (?, ?, ?, ?, ?, ?, ?, ?)`).run(
      id,
      seq,
      publication.kind,
      file.path,
      file.mediaType,
      file.hash,
      file.rendered?.hash ?? null,
      file.rendered?.revision ?? null,
    );
  }
  db.query("UPDATE artifact_versions SET published_at = ? WHERE artifact_id = ? AND seq = ?").run(
    time,
    id,
    seq,
  );
}
