import { Database } from "bun:sqlite";
import { afterEach, beforeEach, describe, expect, test } from "bun:test";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { createArtifactTables } from "./artifact-schema.ts";
import { ArtifactStore } from "./artifacts.ts";
import { BlobStore } from "./blobs.ts";
import { importLegacyContent } from "./migration-content.ts";
import { LEGACY_TABLES, type LegacyData, MigrationContext } from "./migration-data.ts";

let root: string;
let db: Database;
let blobs: BlobStore;
let data: LegacyData;
let store: ArtifactStore;
const time = "2026-09-01T00:00:00.000Z";
const render = async (source: string) => ({
  html: `<article>${source}</article>`,
  revision: "migration-test",
});
const patch = "diff --git a/a.txt b/a.txt\n--- a/a.txt\n+++ b/a.txt\n@@ -1 +1 @@\n-old\n+new\n";

beforeEach(async () => {
  root = await mkdtemp(join(tmpdir(), "r3-migration-content-"));
  db = new Database(":memory:");
  createArtifactTables(db);
  blobs = new BlobStore(join(root, "blobs"));
  store = new ArtifactStore(db, blobs, render, () => time);
  data = Object.fromEntries(LEGACY_TABLES.map((table) => [table, []])) as unknown as LegacyData;
});
afterEach(async () => {
  db.close();
  await rm(root, { recursive: true, force: true });
});

describe("legacy content import", () => {
  test("preserves retained bytes and paths, distinguishes missing markers, and records defaults", async () => {
    data.reviews.push({
      id: "review_files",
      kind: "files",
      created_by: "agent",
      status: "approved",
      meta: '{"session":"known-run"}',
    });
    data.snapshots.push({ review_id: "review_files", seq: 2, label: "Retained snapshot" });
    data.snapshot_files.push(
      {
        review_id: "review_files",
        seq: 2,
        path: "review_files/index.md",
        content: "# Original",
        sha: "old-sha",
      },
      { review_id: "review_files", seq: 2, path: "empty.txt", content: "", sha: "empty-sha" },
      {
        review_id: "review_files",
        seq: 2,
        path: "image.png",
        content: "",
        sha: "missing-sha",
        skipped: 1,
      },
    );
    await importLegacyContent(new MigrationContext(db, data, time), blobs, render);
    expect(store.get("review_files")).toMatchObject({
      kind: "files",
      state: "archived",
      nextSeq: 3,
      createdBy: { role: "agent", sessionId: "known-run" },
    });
    expect(store.files("review_files", 2).map((f) => f.path)).toEqual([
      "empty.txt",
      "review_files/index.md",
    ]);
    expect((await store.readFile("review_files", 2, "empty.txt")).length).toBe(0);
    expect((await store.readFile("review_files", 2, "review_files/index.md")).toString()).toBe(
      "# Original",
    );
    expect(store.file("review_files", 2, "review_files/index.md").rendererRevision).toBe(
      "migration-test",
    );
    expect(store.version("review_files", 2).publishedBy).toEqual({
      role: "human",
      sessionId: null,
    });
    expect(store.version("review_files", 2).provenance).toMatchObject({
      migration: { source: { missing: [{ path: "image.png" }] } },
    });
    expect(store.get("review_files").legacy).toMatchObject({
      migration: { missingVersions: [[1, 1]], source: { status: "approved" } },
    });
    expect(db.query("SELECT * FROM artifact_events").all()).toHaveLength(1);
    expect(db.query("PRAGMA foreign_key_check").all()).toEqual([]);
  });

  test("empty snapshots become explicit notices and new capture follows every historical reference", async () => {
    data.reviews.push({ id: "review_empty", kind: "files", status: "open" });
    data.snapshots.push({ review_id: "review_empty", seq: 1 });
    data.feedback.push({ id: "feedback_ref", review_id: "review_empty" });
    data.replies.push({ id: "reply_ref", feedback_id: "feedback_ref", ref_version: 8 });
    await importLegacyContent(new MigrationContext(db, data, time), blobs, render, async () => ({
      kind: "files",
      files: [
        {
          path: "asset.bin",
          mediaType: "application/octet-stream",
          base64: Buffer.from([0, 255, 128]).toString("base64"),
        },
      ],
    }));
    expect(store.versions("review_empty").map((v) => v.seq)).toEqual([1, 9]);
    expect(store.get("review_empty").nextSeq).toBe(10);
    expect((await store.readFile("review_empty", 1, "MIGRATION.md")).toString()).toContain(
      "generated by r3",
    );
    expect(store.version("review_empty", 1).provenance).toMatchObject({
      migration: {
        defaults: expect.arrayContaining([
          expect.objectContaining({ field: "files", value: ["MIGRATION.md"] }),
        ]),
      },
    });
    expect(await store.readFile("review_empty", 9, "asset.bin")).toEqual(
      Buffer.from([0, 255, 128]),
    );
    expect(store.version("review_empty", 9).provenance).toMatchObject({
      migration: { currentCapture: true, historical: false },
    });
    expect(store.get("review_empty").legacy).toMatchObject({
      migration: { missingVersions: [[2, 8]] },
    });
  });

  test("missing and invalid patch bodies stay evidence and never trigger a fresh git capture", async () => {
    data.reviews.push({ id: "review_diff", kind: "diff", stored_rounds: 1 });
    data.patches.push(
      { review_id: "review_diff", seq: 2, body: patch },
      { review_id: "review_diff", seq: 4, body: "incomplete retained body" },
    );
    data.feedback.push({ id: "feedback_ref", review_id: "review_diff", patch_seq: 7 });
    let captured = false;
    await importLegacyContent(new MigrationContext(db, data, time), blobs, render, async () => {
      captured = true;
      return { kind: "diff", patch };
    });
    expect(captured).toBe(false);
    expect(store.versions("review_diff").map((v) => v.seq)).toEqual([2]);
    expect(store.patch("review_diff", 2)).toBe(patch);
    expect(store.get("review_diff")).toMatchObject({
      nextSeq: 8,
      legacy: {
        migration: {
          missingVersions: [
            [1, 1],
            [3, 7],
          ],
          unavailable: [{ seq: 4, body: "incomplete retained body" }],
        },
      },
    });
    const published = await store.publish("review_diff", {
      expectedSeq: 2,
      publicationKey: "after-migration",
      actor: { role: "human", sessionId: null },
      content: { kind: "diff", patch },
    });
    expect(published.seq).toBe(8);
  });

  test("a files review with no history remains usable offline without inventing an index", async () => {
    data.reviews.push({ id: "review_offline", kind: "doc", source: '{"doc":"notes.md"}' });
    await importLegacyContent(new MigrationContext(db, data, time), blobs, render, async () => ({
      unavailable: "Publisher is offline",
    }));
    expect(store.get("review_offline").kind).toBe("files");
    expect(store.files("review_offline", 1).map((f) => f.path)).toEqual(["MIGRATION.md"]);
    expect(store.version("review_offline", 1).provenance).toMatchObject({
      migration: { synthetic: ["MIGRATION.md"], capture: { unavailable: "Publisher is offline" } },
    });
  });
});
